/**
 * Trace/audit vocabulary. Every mutating action in D-Trace is recorded with one
 * of these actions so the trail stays queryable instead of free-text.
 */
/**
 * The trail records **row changes only**: an insert, an update or a delete.
 *
 * Sign-ins, token refreshes and sign-outs used to live here and no longer do -
 * they change no business data, and at one row per refresh they buried the
 * changes an auditor actually came for. They are emitted as structured log
 * lines instead, for whatever reads the logs.
 *
 * Rows written under the retired actions are still in the table and still
 * readable; this list only governs what is written from now on, and what the
 * filter dropdown offers.
 */
export const AUDIT_ACTIONS = {
  AUTH_REGISTER: 'AUTH_REGISTER',
  AUTH_PASSWORD_CHANGED: 'AUTH_PASSWORD_CHANGED',
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DELETED: 'USER_DELETED',
  USER_ROLE_CHANGED: 'USER_ROLE_CHANGED',
  SETTINGS_UPDATED: 'SETTINGS_UPDATED',
  INVITATION_SENT: 'INVITATION_SENT',
  INVITATION_ACCEPTED: 'INVITATION_ACCEPTED',
  INVITATION_REVOKED: 'INVITATION_REVOKED',
  HOLIDAYS_SYNCED: 'HOLIDAYS_SYNCED',
  HOLIDAY_CREATED: 'HOLIDAY_CREATED',
  HOLIDAY_DELETED: 'HOLIDAY_DELETED',
  NODE_TYPE_CREATED: 'NODE_TYPE_CREATED',
  NODE_TYPE_UPDATED: 'NODE_TYPE_UPDATED',
  NODE_TYPE_DELETED: 'NODE_TYPE_DELETED',
  NODE_CREATED: 'NODE_CREATED',
  NODE_UPDATED: 'NODE_UPDATED',
  NODE_MOVED: 'NODE_MOVED',
  NODE_DELETED: 'NODE_DELETED',
  NODE_ACTIVATION_CHANGED: 'NODE_ACTIVATION_CHANGED',
  DOCUMENT_TEMPLATE_CREATED: 'DOCUMENT_TEMPLATE_CREATED',
  DOCUMENT_TEMPLATE_UPDATED: 'DOCUMENT_TEMPLATE_UPDATED',
  DOCUMENT_TEMPLATE_DUPLICATED: 'DOCUMENT_TEMPLATE_DUPLICATED',
  DOCUMENT_TEMPLATE_DELETED: 'DOCUMENT_TEMPLATE_DELETED',
  DOCUMENT_TEMPLATE_ASSET_UPLOADED: 'DOCUMENT_TEMPLATE_ASSET_UPLOADED',
  PROJECT_CREATED: 'PROJECT_CREATED',
  PROJECT_UPDATED: 'PROJECT_UPDATED',
  PROJECT_DELETED: 'PROJECT_DELETED',
  PROJECT_TASK_CREATED: 'PROJECT_TASK_CREATED',
  PROJECT_TASK_UPDATED: 'PROJECT_TASK_UPDATED',
  PROJECT_TASK_DELETED: 'PROJECT_TASK_DELETED',
  PROJECT_BUG_CREATED: 'PROJECT_BUG_CREATED',
  PROJECT_BUG_UPDATED: 'PROJECT_BUG_UPDATED',
  PROJECT_BUG_DELETED: 'PROJECT_BUG_DELETED',
  TEST_SCRIPT_SAVED: 'TEST_SCRIPT_SAVED',
  TEST_SCRIPT_SUBMITTED: 'TEST_SCRIPT_SUBMITTED',
  TEST_SCRIPT_CAPTURE_UPLOADED: 'TEST_SCRIPT_CAPTURE_UPLOADED',
  IMPLEMENTATION_PLAN_SAVED: 'IMPLEMENTATION_PLAN_SAVED',
  IMPLEMENTATION_PLAN_COMPLETED: 'IMPLEMENTATION_PLAN_COMPLETED',
  DOCUMENT_CREATED: 'DOCUMENT_CREATED',
  DOCUMENT_UPDATED: 'DOCUMENT_UPDATED',
  DOCUMENT_DELETED: 'DOCUMENT_DELETED',
  DOCUMENT_VERSION_RESTORED: 'DOCUMENT_VERSION_RESTORED',
  DOCUMENT_VERSION_SAVED: 'DOCUMENT_VERSION_SAVED',
  DOCUMENT_FILE_UPLOADED: 'DOCUMENT_FILE_UPLOADED',
  DOCUMENT_FILE_DELETED: 'DOCUMENT_FILE_DELETED',
  MANDAY_PLAN_DECIDED: 'MANDAY_PLAN_DECIDED',
  MANDAY_PLAN_SUBMITTED: 'MANDAY_PLAN_SUBMITTED',
  MANDAY_PLAN_SAVED: 'MANDAY_PLAN_SAVED',
  DOCUMENT_ACCESS_CHANGED: 'DOCUMENT_ACCESS_CHANGED',
  PROJECT_MEMBER_REMOVED: 'PROJECT_MEMBER_REMOVED',
  PROJECT_MEMBER_UPDATED: 'PROJECT_MEMBER_UPDATED',
  PROJECT_MEMBER_ADDED: 'PROJECT_MEMBER_ADDED',
  PERMISSION_MATRIX_UPDATED: 'PERMISSION_MATRIX_UPDATED',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

export const AUDIT_ACTION_VALUES = [
  AUDIT_ACTIONS.AUTH_REGISTER,
  AUDIT_ACTIONS.AUTH_PASSWORD_CHANGED,
  AUDIT_ACTIONS.USER_CREATED,
  AUDIT_ACTIONS.USER_UPDATED,
  AUDIT_ACTIONS.USER_DELETED,
  AUDIT_ACTIONS.USER_ROLE_CHANGED,
  AUDIT_ACTIONS.SETTINGS_UPDATED,
  AUDIT_ACTIONS.INVITATION_SENT,
  AUDIT_ACTIONS.INVITATION_ACCEPTED,
  AUDIT_ACTIONS.INVITATION_REVOKED,
  AUDIT_ACTIONS.HOLIDAYS_SYNCED,
  AUDIT_ACTIONS.HOLIDAY_CREATED,
  AUDIT_ACTIONS.HOLIDAY_DELETED,
  AUDIT_ACTIONS.NODE_TYPE_CREATED,
  AUDIT_ACTIONS.NODE_TYPE_UPDATED,
  AUDIT_ACTIONS.NODE_TYPE_DELETED,
  AUDIT_ACTIONS.NODE_CREATED,
  AUDIT_ACTIONS.NODE_UPDATED,
  AUDIT_ACTIONS.NODE_MOVED,
  AUDIT_ACTIONS.NODE_DELETED,
  AUDIT_ACTIONS.NODE_ACTIVATION_CHANGED,
  AUDIT_ACTIONS.DOCUMENT_TEMPLATE_CREATED,
  AUDIT_ACTIONS.DOCUMENT_TEMPLATE_UPDATED,
  AUDIT_ACTIONS.DOCUMENT_TEMPLATE_DUPLICATED,
  AUDIT_ACTIONS.DOCUMENT_TEMPLATE_DELETED,
  AUDIT_ACTIONS.DOCUMENT_TEMPLATE_ASSET_UPLOADED,
  AUDIT_ACTIONS.PROJECT_CREATED,
  AUDIT_ACTIONS.PROJECT_UPDATED,
  AUDIT_ACTIONS.PROJECT_DELETED,
  AUDIT_ACTIONS.PROJECT_TASK_CREATED,
  AUDIT_ACTIONS.PROJECT_TASK_UPDATED,
  AUDIT_ACTIONS.PROJECT_TASK_DELETED,
  AUDIT_ACTIONS.PROJECT_BUG_CREATED,
  AUDIT_ACTIONS.PROJECT_BUG_UPDATED,
  AUDIT_ACTIONS.PROJECT_BUG_DELETED,
  AUDIT_ACTIONS.TEST_SCRIPT_SAVED,
  AUDIT_ACTIONS.TEST_SCRIPT_SUBMITTED,
  AUDIT_ACTIONS.TEST_SCRIPT_CAPTURE_UPLOADED,
  AUDIT_ACTIONS.IMPLEMENTATION_PLAN_SAVED,
  AUDIT_ACTIONS.IMPLEMENTATION_PLAN_COMPLETED,
  AUDIT_ACTIONS.DOCUMENT_CREATED,
  AUDIT_ACTIONS.DOCUMENT_UPDATED,
  AUDIT_ACTIONS.DOCUMENT_DELETED,
  AUDIT_ACTIONS.DOCUMENT_VERSION_RESTORED,
  AUDIT_ACTIONS.DOCUMENT_VERSION_SAVED,
  AUDIT_ACTIONS.DOCUMENT_FILE_UPLOADED,
  AUDIT_ACTIONS.DOCUMENT_FILE_DELETED,
  AUDIT_ACTIONS.MANDAY_PLAN_DECIDED,
  AUDIT_ACTIONS.MANDAY_PLAN_SUBMITTED,
  AUDIT_ACTIONS.MANDAY_PLAN_SAVED,
  AUDIT_ACTIONS.DOCUMENT_ACCESS_CHANGED,
  AUDIT_ACTIONS.PROJECT_MEMBER_REMOVED,
  AUDIT_ACTIONS.PROJECT_MEMBER_UPDATED,
  AUDIT_ACTIONS.PROJECT_MEMBER_ADDED,
  AUDIT_ACTIONS.PERMISSION_MATRIX_UPDATED,
] as const;

/**
 * Every `entity` value `AuditService.record()` is called with.
 *
 * Here rather than in the web app because the filter dropdown and the API's
 * `entity` query parameter have to agree on the spelling — a typo would
 * silently return an empty page instead of failing.
 */
export const AUDIT_ENTITY_VALUES = [
  'AppSetting',
  'DocumentTemplate',
  'Holiday',
  'ImplementationPlan',
  'Invitation',
  'Node',
  'NodeType',
  'ProjectBug',
  'ProjectRolePermission',
  'ProjectTask',
  'Session',
  'TestScript',
  'TestScriptCapture',
  'User',
] as const;

export type AuditEntity = (typeof AUDIT_ENTITY_VALUES)[number];
